# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='ChatUser',
        ),
    ]
