# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0002_auto_20171101_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatUser',
            new_name='ChatAccount',
        ),
    ]
