# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 18:17
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User
from django.conf import settings

def create_default_user(apps, schema_editor):
  default_user = User.objects.create_user(settings.DEFAULT_USER_NAME, password=settings.DEFAULT_USER_PASSWORD)
  default_user.is_staff = True
  default_user.is_superuser = True
  default_user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0004_auto_20171105_1816'),
    ]

    operations = [
        migrations.RunPython(create_default_user),
    ]
