# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 18:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('explorer', '0005_auto_20171105_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='chataccount',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
