# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0006_chataccount_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chataccount',
            old_name='user_id',
            new_name='user',
        ),
    ]
