# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 21:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('explorer', '0008_chataccount_signed_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_account', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='explorer.ChatAccount')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
