# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0012_chatchannel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='remote_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='from_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='to_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
