# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0013_auto_20171106_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='timestamp',
            new_name='date',
        ),
    ]
