# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0014_auto_20171106_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='author_name',
            field=models.CharField(default='', max_length=4096),
        ),
    ]
