# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0015_chatmessage_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='to_id',
        ),
    ]
