# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0016_remove_chatmessage_to_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chataccount',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatchannel',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
