# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0017_auto_20171106_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chataccount',
            old_name='type',
            new_name='ttype',
        ),
        migrations.RenameField(
            model_name='chatchannel',
            old_name='type',
            new_name='ttype',
        ),
    ]
