# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0018_auto_20171106_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chataccount',
            name='ttype',
        ),
        migrations.RemoveField(
            model_name='chatchannel',
            name='ttype',
        ),
    ]
