# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0019_auto_20171106_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='chataccount',
            name='ttype',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatchannel',
            name='ttype',
            field=models.IntegerField(default=0),
        ),
    ]
