# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 12:11
from __future__ import unicode_literals

from django.db import migrations
from explorer.models import MessengerType, ChatType
from django.conf import settings

def create_types(apps, schema_editor):
  pass

class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0021_channeltype_messengertype'),
    ]

    operations = [
        migrations.RunPython(create_types),
    ]
