# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0022_auto_20171106_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chataccount',
            name='ttype',
        ),
        migrations.AddField(
            model_name='chataccount',
            name='messenger_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='explorer.MessengerType'),
        ),
    ]
