# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0026_auto_20171106_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='daytime',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Morning'), (2, 'Day'), (3, 'Evening'), (4, 'Night')], default=0),
        ),
    ]
