# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0027_message_daytime'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat_id', 'remote_id'], name='explorer_me_chat_id_7ac20d_idx'),
        ),
    ]
