# Generated by Django 3.1.3 on 2021-01-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0031_auto_20181014_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author_username',
            field=models.CharField(default='', max_length=4096),
        ),
    ]
