# Generated by Django 3.1.3 on 2021-01-18 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0032_message_author_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author_username', models.CharField(default='', max_length=4096)),
                ('role', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Admin'), (2, 'Bot')], default=0)),
                ('chat', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='explorer.chat')),
            ],
        ),
    ]
