# Generated by Django 3.1.3 on 2021-01-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0033_authorrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorrole',
            old_name='author_username',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='authorrole',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Bot')], default=0),
        ),
    ]
