# Generated by Django 3.1.3 on 2021-01-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0034_auto_20210118_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorrole',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='authorrole',
            constraint=models.UniqueConstraint(fields=('chat', 'username'), name='chat__username'),
        ),
    ]
